
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-ast
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=2048']
        exclude: ^logo/
      - id: detect-private-key
      - id: forbid-new-submodules
      - id: pretty-format-json
        args: ['--autofix', '--no-sort-keys', '--indent=4']
      - id: end-of-file-fixer
        exclude: .ipynb
      - id: mixed-line-ending
        args: [ '--fix=auto' ]
      - id: debug-statements

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.8.0
    hooks:
    -   id: pyupgrade
        args:
        - --py3-plus
        - --keep-runtime-typing
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.276
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/bandit
    rev: '1.7.5'
    hooks:
    -   id: bandit
        language_version: python3

        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.2.0
    hooks:
    -   id: autoflake

-   repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
    -   id: nbstripout

ci:
    autofix_commit_msg: "fix(pr): 🎨 auto format pre-commit hooks"
    autoupdate_commit_msg: "fix(pr): ⬆ auto pre-commit update"
