name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Set up a virtual environment for Python
        run: |
          python -m pip install --upgrade virtualenv
          python -m venv venv
          if [ "$RUNNER_OS" == "Windows" ]; then
            .\venv\Scripts\Activate
          else
            source venv/bin/activate
          fi

      - name: Install the base dependencies
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            .\venv\Scripts\Activate
          else
            source venv/bin/activate
          fi
          python -m pip install --upgrade poetry

      - name: Check the correctness of the project config
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            .\venv\Scripts\Activate
          else
            source venv/bin/activate
          fi
          poetry check

      - name: Install the package
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            .\venv\Scripts\Activate
          else
            source venv/bin/activate
          fi
          poetry install

      - name: Run tests
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            .\venv\Scripts\Activate
          else
            source venv/bin/activate
          fi
          pytest -v
