name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install pdm
        run: |
          python -m pip install --upgrade pdm

      - name: Install the base dependencies
        run: |
          pdm install --dev

      - name: Install pytest
        run: |
          pdm add pytest

      - name: Install the package
        run: |
          pdm install

      - name: Run tests
        run: |
          pdm run pytest -v
