name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Set up a virtual environment for Python
        if: runner.os == 'Windows'
        run: |
          python -m venv venv
          call venv\Scripts\activate.bat

      - name: Install the base dependencies
        if: runner.os == 'Windows'
        run: |
          venv\Scripts\activate.bat
          python -m pip install --upgrade poetry

      - name: Check the correctness of the project config
        if: runner.os == 'Windows'
        run: |
          venv\Scripts\activate.bat
          poetry check

      - name: Install the package
        if: runner.os == 'Windows'
        run: |
          venv\Scripts\activate.bat
          poetry install

      - name: Run tests
        if: runner.os == 'Windows'
        run: |
          venv\Scripts\activate.bat
          pytest -v
