name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up a virtual environment for Python ${{ matrix.python-version }}
        run: |
          python -m pip install --upgrade virtualenv
          virtualenv venv
          source venv/bin/activate

      - name: Install the base dependencies
        run: |
          source venv/bin/activate
          python -m pip install --upgrade poetry

      - name: Check the correctness of the project config
        run: |
          source venv/bin/activate
          poetry check

      - name: Install the package
        run: |
          source venv/bin/activate
          poetry install

      - name: Run tests
        needs: [build-test]
        run: |
          source venv/bin/activate
          pytest -v
